Add homepage tsx and css
JDaniielC/almocin pull request #57
Opened 2024-07-12 18:13 UTC by lpstrevisan

2024-07-12 19:36 UTC, JDaniielC requested changes
You'd improve this page following the design (search for first canva project)

2024-07-12 19:36 UTC, JDaniielC commented on frontend/src/app/home/pages/homePage/index.tsx
> +            <button className="menu-buttons"> Estatísticas do Usuário </button>
User Statistics doesn't exists.

2024-07-16 12:36 UTC, JDaniielC requested changes
Refactor baseLayout reuse and remove menuContext

2024-07-16 12:36 UTC, JDaniielC commented on frontend/src/app/home/components/baseLayout/index.tsx
It's better move baseLayout for shared and create menuItems for each module (home, admin)

2024-07-16 12:36 UTC, JDaniielC commented on frontend/src/app/itemMenu/components/baseLayout/index.tsx
Again, reuse code.

2024-07-16 12:36 UTC, JDaniielC commented on frontend/src/app/itemMenu/context/itemMenuContext/index.tsx
menuContext already exists.

2024-07-18 14:43 UTC, lpstrevisan commented on frontend/src/app/home/components/baseLayout/index.tsx
i didn't understand "create menuItems for each module", there is already a "menu" in admin module, should I just move the itemMenu to home module?

2024-07-21 01:10 UTC, JDaniielC approved these changes

2024-07-21 03:24 UTC, merged